apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: azure-keyvault-cluster-store
    kind: ClusterSecretStore
  target:
    name: pihole-password
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
    remoteRef:
      key: pihole-password
