https://github.com/zaldre/blog/blob/main/code/eso/pihole-helm.ymlapiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-cloudflare
  namespace: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns-cloudflare
  template:
    metadata:
      labels:
        app: external-dns-cloudflare
    spec:
      serviceAccountName: external-dns-cloudflare
      containers:
        - name: external-dns
          resources: {}
          image: registry.k8s.io/external-dns/external-dns:v0.19.0
          args:
            - --source=ingress
            - --annotation-filter=external-dns.alpha.kubernetes.io/hostname
            - --force-default-targets
            - --default-targets=203.12.13.206
            - --provider=cloudflare
            - --txt-prefix=edns- 
            - --txt-owner-id=default
            - --cloudflare-dns-records-per-page=5000 
            - --cloudflare-record-comment="provisioned by external-dns" # (optional) configure comments for provisioned records; <=100 chars for free zones; <=500 chars for paid zones
          env:
              - name: CF_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: cloudflareapikey
                    key: cloudflareapikey
              - name: CF_API_EMAIL
                valueFrom:
                  secretKeyRef:
                    name: cloudflareapikey
                    key: email