apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: pihole
spec:
  refreshPolicy: Periodic
  refreshInterval: 24h 
  secretStoreRef:
    name: azure-keyvault-cluster-store
    kind: ClusterSecretStore
  target:
    name: pihole-password
    creationPolicy: Owner
  data:
  - secretKey: pihole-password
    remoteRef:
      key: pihole-password