theme = 'PaperMod'
baseURL = 'https://zaldre.com/'
relativeURLs = true
canonifyURLs = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "Zaldre"
  description = "Coding, infrastructure, automation and general tech tom foolery"
  # Add your social links if desired
  github = "zaldre"
  # twitter = "your-handle"

[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows HTML in markdown

[menu]
  [[menu.main]]
    name = "posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "about me"
    url = "/about/"
    weight = 2